export {
  FLASH_ACCENT_STYLES,
  FLASH_DURATION_MS,
  FLASH_HOLD_MS,
  FLASH_RAMP_DOWN_MS,
  FLASH_RAMP_UP_MS,
  collectUnreadPaneIds,
  countUnreadPanes,
  createAttentionStore,
  getFlashOpacity,
  selectAttentionSnapshot,
  selectWorkspaceAttentionSnapshot,
  useAttentionSignal,
  useAttentionSnapshot,
  usePaneAttentionState,
} from './store.js';
export type {
  AttentionActions,
  AttentionFlash,
  AttentionSignal,
  AttentionSnapshot,
  AttentionStore,
  AttentionStoreState,
  CreateAttentionStoreOptions,
  FlashAccent,
  FlashAccentStyle,
  FlashReason,
  FocusPaneInput,
  HydrateAttentionWorkspaceInput,
  ManualUnreadInput,
  PaneAttentionState,
  WorkspaceAttentionSnapshot,
} from './store.js';
